wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.8
    framework: xgboost
    huggingface_version: 4.33.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1699200668.922693
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 71
      - 105
      2:
      - 1
      - 5
      - 6
      - 11
      - 49
      - 53
      - 55
      - 71
      - 105
      3:
      - 23
      4: 3.10.11
      5: 0.15.8
      6: 4.33.1
      8:
      - 2
      - 5
